probabilistic-numerics/probnum

.travis.yml
Travis CI has removed support for `sudo: false` in an effort to unify their build infrastructures, see https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.
As for `dist: xenial`: xenial is the default distribution as of April 2019, see https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment, and doesn't need to be specified.
=> Remove obsolete options in .travis.yml

.travis.yml, CONTRIBUTING.md, docs/source/development/example_notebook.md, tox.ini
See Issue #73 for more information and a thorough discussion.
Currently, this PR provides basic functionality to run tests and build documentation locally with tox.
Missing:
=> Use tox to run tests and build documentation

src/probnum/prob/randomvariable.py
I have the impression, that in most occurrence in our codebase `RandomVariable`s are built with 
```python
from probnum.prob import RandomVariable, Normal
X = RandomVariable(distribution=Normal(0, 1))
```
I'm strongly in favor of changing the order of the `RandomVariable.__init__` arguments such that the first argument is the distribution. The result is a less verbose handling, looking as follows:
```python
from probnum.prob import RandomVariable, Normal
X = RandomVariable(Normal(0, 1))
```
I found <10 occurrences in which the RV is not built out of a distribution, but a `shape`, but in all of those the name of the function argument ("shape") got passed explicitly.
Also, all tests pass, so this should not break anything :)
=> Re-order the RandomVariable arguments for convenience

src/probnum/diffeq/odefiltsmooth/prior.py
For the IBM, the computation of A(h) and Q(h) is now fully vectorised. The corresponding unittests go down from 8s to roughly 5-6s (which is the only performance tests I have tried). Notably, for A(h) looping over the diagonal elements (diagonal->first offdiagonal->second offdiagonal etc.) is faster than a fully vectorised, numpy based implementation (5.5s vs 7s). I suppose this is because scipy.special.factorial---albeit being able to handle matrices as inputs---is much slower than np.math.factorial (see https://stackoverflow.com/questions/21753841/factorial-in-numpy-and-scipy).
=> Vectorise ah qh

.travis.yml, tox.ini
Closes #127 
I moved away from tox-travis and just specify the jobs directly, including the python version and tox environment. As a byproduct the Travis-CI even got a bit better organized.
=> Fix Travis and tox to properly test python 3.6, 3.7 and 3.8

src/probnum/prob/distributions/dirac.py, src/probnum/prob/distributions/distribution.py, src/probnum/prob/distributions/normal.py, src/probnum/prob/randomvariable.py, src/probnum/utils/scalarutils.py, tests/test_prob/test_distributions/test_normal.py, tests/test_prob/test_randomvariable.py
This PR enables full numpy-style indexing for random variables and distributions (currently Normal and Dirac) as in
https://numpy.org/doc/stable/reference/arrays.indexing.html
Closes #11.
=> (Advanced) Indexing, Slicing, Masking, Reshaping and Transposition for Random Variables and Distributions

tox.ini
This PR fixes coverage reports. Currently coverage reports are not uploaded to codecov. Previously `doctests` also quietly were not run by `tox`. This PR fixes this issue as well.
This closes #139 .
=> updated coverage settings for pytest

pyproject.toml, tox.ini
This fixes #170. To make the CI tests pass again, I also added an additional exception for "raise-missing-from" to `probnum.prob` (see #159 for all).
=> Pinned pylint to 2.6 and updated the configs accordingly

src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py, src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py, src/probnum/diffeq/odesolver.py
steprule is now an argument for solve(), not an attribute of the solver. This is the first step of the refactoring, but independent enough that it can be merged independently.
=> Refactor diffeq

docs/source/conf.py, src/probnum/filtsmooth/gaussfiltsmooth/_utils.py, src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py, src/probnum/filtsmooth/gaussfiltsmooth/kalman.py, src/probnum/prob/distributions/dirac.py, src/probnum/prob/distributions/distribution.py, src/probnum/prob/distributions/normal.py, src/probnum/prob/randomvariable.py, tests/test_prob/test_distributions/test_normal.py, tests/test_utils/test_arrayutils.py, tox.ini
Solves #184, so the CI should not fail anymore.
I pinned Black to the latest version 20.8b0 (so the version that would be installed by a new user when freshly installing Black). I would advise everybody (pinging @JonathanWenger @pnkraemer @marvinpfoertner) to install the latest Black version locally (`pip install black==20.8b0`) in order to reduce the mismatch between CI checks and the local formatting.
=> Bumped and pinned Black, and applied it once to the codebase

src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py, src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py, src/probnum/diffeq/odesolution.py, src/probnum/diffeq/odesolver.py, tests/test_diffeq/test_odesolver.py
solve() is part of ODESolver now. I needed to put some hotfixes into ODESolution because now it cant depend on filtering methods in all generality anymore. This will be resolved in the future, I suggest. 
To implement a new ODESolver, one has to provide an initialise() method (which returns t0 and  y0) and a step method (which returns a guess and an error estimate). To ensure that this is enough, I wrote a test where those two are implemented for Euler. Other changes:
* _suggest_step and other attributes/methods are moved to ODEsolver, too
* smoothing is part of postprocess
If you have any questions, please comment :)
=> Refactor odesolver

tox.ini
With the current CI setup while benchmarks were run in `dev` mode with airspeed velocity, asv did not actually return non-zero exit code on failure. This is only possible with the newest version on Github and its `--strict` flag. This PR now ensures that the tox environment for the benchmarks actually fails if there is a breaking code change in the benchmarks.
=> Adjusted tox config such that asv fails on benchmark error

CONTRIBUTING.md, README.md, docs/source/index.rst
Travis is migrating all its repositories from https://travis-ci.org to https://travis-ci.com by Dec 31st, 2020 (see also: https://docs.travis-ci.com/user/migrate/open-source-repository-migration)
> As you’ll no doubt have noticed, Travis CI has, for some time, been split between travis-ci.com and travis-ci.org. This was initially planned to enable open-source and commercial/private projects to be distinctly separate, but back in May 2018, we announced that open source builders would have the opportunity to build and test their projects under travis-ci.com, meaning your public and private repositories could be managed under one domain with a consistent interface and build environment.
In order to facilitate this change I performed the migration and updated any links in the repository. …
=> Travis Migration to travis-ci.com

docs/requirements.txt
ReadtheDocs is now set up to also build PR branches. During this change a build failure related to the pygments version appeared. This PR fixes a minimal version.
=> Fixed pygments version to avoid readthedocs build failures

src/probnum/linalg/linearsolvers/matrixbased.py, tests/test_linalg/test_linearsolvers/test_linearsolvers.py
When specifying a constant for uncertainty calibration in the probabilistic linear solver, due to misplaced parentheses the wrong calibration mode (or none) was chosen. This resulted in false warnings and no calibration. This PR also fixes a currently faulty test.
=> Calibration mode was not always used in the probabilistic linear solver

tox.ini
Running pylint (`tox -e pylint`) is awfully slow, at least on my machine. However, seems like it can be executed in parallel (https://stackoverflow.com/questions/51488322/why-pylint-is-too-slow-while-pep8-just-takes-a-second-to-check-the-same-code)
The speed-up gained by adding `--jobs=0` (which auto-detects the number of CPUs) is ~50s vs ~75s, which is not the world, but better than nothing. Seems like the biggest speed-up here was in the tests: ~30s vs ~10s. 
Do we want to have this in `tox.ini`? If so, please review :)
=> Speed up pylint

codecov.yml
Codecov checks often failed in PRs in the past where no or only minor changes were made to the codebase. The introduction of the config file reduces the strictness of codecov and should mostly avoid such issues in the future.
=> Reduced strictness of codecov via config file

src/probnum/diffeq/__init__.py, src/probnum/diffeq/ode/__init__.py, src/probnum/diffeq/odefiltsmooth/__init__.py, src/probnum/filtsmooth/__init__.py, src/probnum/filtsmooth/gaussfiltsmooth/__init__.py, src/probnum/filtsmooth/statespace/__init__.py, src/probnum/filtsmooth/statespace/sde.py, tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
The name says it all.
No more star imports in `__init__.py` files (in diffeq and filtsmooth). This avoids weird exports of `statespace.numpy` and the like.
=> Remove star imports from diffeq and filtsmooth (and filtsmooth.statespace)

src/probnum/filtsmooth/gaussfiltsmooth/kalman.py, src/probnum/filtsmooth/statespace/transition.py, tests/test_filtsmooth/test_gaussfiltsmooth/filtsmooth_testcases.py, tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py, tests/test_filtsmooth/test_statespace/test_transition.py
Fixes #303 and introduces minor documentation for Kalman filter initialisation, which was missing (as pointed out by Nina). 
The main difference to before is that the initial random variable in the filter is the location of the first data point! (Which makes a million times more sense?!). The rest is making sure that all the shape tests (which now break ofc) are corrected.
=> Fixed kalman initial data points

docs/source/development/unit_testing.ipynb
This PR updates the developer documentation to reference `pytest` instead of `unittest`. this is in line with our recent decision to switch the testing framework.
=> updated developer docs to pytest

pyproject.toml, setup.cfg, src/probnum/diffeq/odefiltsmooth/initialise.py, tox.ini
For the last few commits doctests were not run anymore. This PR fixes the test collection.
This problem occurred since I erroneously had removed the `src` directory from the test path in an attempt to fix an `ImportPathError` which is explained in detail here: https://github.com/tox-dev/tox/issues/373 as part of #263. Essentially 
when using `tox` with `pytest`, then the following scenario arises:
> the problem is - your test imports the installed module thats inside the virtualenv
> afterwards doctest-modules comes along and takes a look at the source modules trying to import them failing with a mismatch
The current recommended fix by the `tox` developers is to use the `testenv` option `usedevelop = True`.
Additionally I moved the pytest config out of `setup.cfg` in a steady migration …
=> Fix doctest collection

.github/workflows/python-publish.yml, .gitignore, setup.cfg, setup.py
Versioning was previously handled by a commit triggered on release of a new version. This was broken (see #293) due to a lack of permissions. This mechanism is now replaced by [`setuptools_scm`](https://github.com/pypa/setuptools_scm/), which reads the version from the git tag, which is automatically created when a release is triggered.
Closes #293
=> Automated versioning based on package metadata

setup.cfg, src/probnum/linops/_arithmetic.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/randvars/_normal.py, tests/test_linops/test_kronecker.py, tests/test_linops/test_linearoperators.py, tests/test_linops/test_linops.py, tests/test_linops/test_linops_cases/kronecker_cases.py, tests/test_linops/test_linops_cases/linear_operator_cases.py
This PR refactors the current tests (excluding arithmetic tests) for linear operators to use pytest and pytest-cases.
It also makes existing tests stricter and adds new tests.
=> Refactor linop testing using pytest-cases

src/probnum/statespace/discrete_transition.py
This PR replaces all `inv` and `solve` by more appropriate replacements. This has a surprisingly big impact on the square-root transitions in terms of stability and dealing with really ill-conditioned matrices. 
(This impact I noticed when working with the code, there is no proof I can show here :))
=> Stabilise matrix inversion in discrete transitions

benchmarks/linops.py
Prepares for #381.
- Rename `diagonal`-> `scaling`
- Add benchmark for `LinearOperator.__init__`
=> Update linop benchmarks

benchmarks/filtsmooth.py, docs/source/tutorials/filtsmooth/linear_gaussian_filtering_smoothing.ipynb, docs/source/tutorials/filtsmooth/nonlinear_gaussian_filtering_smoothing.ipynb, docs/source/tutorials/filtsmooth/particle_filtering.ipynb, src/probnum/diffeq/odefiltsmooth/initialize.py, src/probnum/filtsmooth/gaussfiltsmooth/kalman.py, src/probnum/filtsmooth/particlefiltsmooth/_particle_filter.py, tests/test_diffeq/test_odefiltsmooth/test_kalman_odesolution.py, tests/test_filtsmooth/filtsmooth_testcases.py, tests/test_filtsmooth/test_gaussfiltsmooth/test_iterated_kalman.py, tests/test_filtsmooth/test_gaussfiltsmooth/test_kalman.py, tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py, tests/test_filtsmooth/test_particlefiltsmooth/test_particle_filter.py
This PR implements Kalman filtering methods as generators in order to make partial results accessible.
=> Implement filtsmooth methods as generators

src/probnum/linops/_linear_operator.py, tests/test_linops/test_linops_cases/linear_operator_cases.py
The function `scipy.sparse.linalg.inv()` emits a warning when given an `spmatrix` in a format other that 'csc'.
This PR
* converts the matrix to 'csc' format prior to calling the inversion routine.
* adds test cases for `Matrix` wrapping `scipy.sparse.spmatrix`
=> Fix warning in `.inv()` of `LinearOperator`s of type `Matrix` wrapping `scipy.sparse.spmatrix` 

src/probnum/problems/zoo/linalg/_random_spd_matrix.py, tests/test_problems/test_zoo/test_linalg/test_random_spd_matrix.py
With the recent changes to `random_sparse_spd_matrix` in #455 , the function now returns a sparse matrix. However, the input arguments restricting the range of entries in the Cholesky factor was no longer considered and also the output sparsity format was not tested.
=> Improved implementation of `random_sparse_spd_matrix`

setup.cfg
#382 introduced test code which necessitates `pytest_cases>=3.5`. See also discussion in #398.
=> Fixed pytest_cases to correct version

src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py, src/probnum/filtsmooth/_gaussfiltsmooth/_kalman.py, src/probnum/filtsmooth/_gaussfiltsmooth/_kalmanposterior.py, src/probnum/filtsmooth/_timeseriesposterior.py, tests/test_filtsmooth/test_gaussfiltsmooth/test_kalmanposterior.py
Builds the filtering posterior on the fly, i.e. directly builds up the `FilteringPosterior` object, which is returned in the end.
This happens by
- allowing for initializing an empty `TimeSeriesPosterior` object
- adding an `.append(loc, rv)` method to the `TimeSeriesPosterior` class
=> Build FilteringPosterior on the fly

src/probnum/statespace/discrete_transition.py, src/probnum/statespace/integrator.py, tests/test_statespace/test_integrator.py
Where applicable, let `Transition`s return forwarded random variables in the `.backward()` call. Might be useful e.g. for computing marginal likelihoods during filtering/smoothing.
=> Return forwarded RV

README.md, benchmarks/asv.conf.json, docs/source/development/creating_an_example_notebook.ipynb, docs/source/development/pull_request.md, docs/source/tutorials.rst
In preparation for the branch renaming `master` -> `main` in accordance with the community guidelines, this replaces all references in the repository to the master branch with main.
This closes #402
=> Replace all references to the master branch with main

docs/source/_templates/footer.html, docs/source/_templates/index.html, docs/source/research.md, docs/source/tutorials/pn_methods.ipynb
Renames the navigation option on the landing page from "Research" to "Probabilistic Numerics".
=> Website Navigation Bar Update

docs/source/_ext/probnum-config-options.py, docs/source/api.rst, docs/source/conf.py, src/probnum/__init__.py, src/probnum/_config.py, src/probnum/randvars/_normal.py, tests/test_config.py
This PR implements a custom Sphinx extension which generates a table documenting the available configuration options automatically.
- ~[ ] add iterator over registered `Configuration.Option`s~
=> Auto-generate documentation for `probnum.config` options

.github/workflows/python-publish.yml
This PR fixes a bug in the glob pattern used to upload ProbNum wheels to PyPI.
See above.
None
=> Bugfix: Deploy to PyPI

docs/source/tutorials/linalg/linear_solvers_quickstart.ipynb
One formula does not render correctly it seems in the docs corresponding to notebook introduced in PR #511 . In the initial PR, the notebook looked OK when building the page locally, so no entirely sure if this PR will fix it (although I suspect it will). 
Added a blank line in the Markdown cell with the LaTeX formula.
Closes #...
=> fix rendering of formula in linsolver quickstart

.github/workflows/run-notebooks.yml, docs/source/research/bibliography/related.bib
The Github Action running the notebooks kept failing. This bug is likely caused by an outdated `apt` cache. This PR adds `sudo apt-get update` to the action.
The Github Action running the notebooks displayed the following error:
```bash
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.50~dfsg-5ubuntu4.2_all.deb  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9_9.50~dfsg-5ubuntu4.2_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/ghostscript/ghostscript_9.50~dfsg-5ubuntu4.2_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
``` …
=> Update `apt` cache in Github action running notebooks

benchmarks/randprocs.py, src/probnum/_config.py, src/probnum/randprocs/markov/discrete/_linear_gaussian.py, src/probnum/randprocs/markov/integrator/_iwp.py, src/probnum/randprocs/markov/integrator/_preconditioner.py, src/probnum/randvars/_constant.py, tests/test_randprocs/test_markov/test_discrete/test_linear_gaussian.py, tests/test_randprocs/test_markov/test_integrator/test_iwp.py, tests/test_randvars/test_constant.py, tests/test_randvars/test_normal.py
This PR gives a more descriptive name (`matrix_free`) to the configuration option which uses linear operators instead of full matrices.
The term `matrix_free` is a more complete description of what functionality `LinearOperator`s offer, namely that they
- only implicitly define the matrix-vector product
- generally do not instantiate a full matrix in memory
- are memory and time-efficient
- offer lazy arithmetic
=> Rename `lazy_linalg` config option `matrix_free`

setup.cfg
The test discovery fails on Python 3.8.10 or older with the most recent version of `pytest`.
Note that this bug was not caught by our CI since it tests with the most recent Python 3.8.x (currently x=12). 
The following error appears if using `pytest>6.1` with Python 3.8.10:
```bash
======================================== test session starts ========================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/j/Documents/Professional/research/code/probnum/.tox/py3/bin/python
cachedir: .tox/py3/.pytest_cache
rootdir: /home/j/Documents/Professional/research/code/probnum, configfile: pyproject.toml, testpaths: src, tests
plugins: cov-3.0.0, cases-3.6.4
collected 0 items / 1 error …
```
=> Pytest version pinned for Python 3.8.10 or older

src/probnum/linops/_arithmetic.py, src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/linops/_scaling.py, tests/test_linops/test_arithmetics.py, tests/test_linops/test_linops.py
This PR removes support for `np.complexfloating` dtypes from the `LinearOperator`.
At the moment, our linear operator has rudimentary support for complex numbers, but it is largely untested and makes the code more complex than it needs to be.
Since we don't use this feature right now and are unlikely to need it in the future, it is better to just remove the - possibly faulty - code alltogether.
If we do need the feature in the future, it is better to reintroduce the feature cleanly with tests and proper documentation.
None
=> Remove support for complex dtypes from `LinearOperator`

src/probnum/_config.py, src/probnum/linops/_arithmetic.py, src/probnum/linops/_linear_operator.py, tests/test_linops/test_arithmetics.py
Currently, the `lazy_matrix_matrix_matmul` config option computes `Matrix` @ `Matrix` lazily if it is set to `False`, which is counterintuitive.
This PR inverts the semantics of the flag such that setting it to `True` enables lazy computation.
- inverted the semantivs of `lazy_matrix_matrix_matmul` config flag
- refactored the documentation of `matrix_free` and `lazy_matrix_matrix_matmul` to link `LinearOperator` and `Matrix` to the API docs
None
=> Invert semantics of `lazy_matrix_matrix_matmul` config option

src/probnum/linops/_linear_operator.py, tests/test_linops/test_linops.py
This PR adds a NumPy-style `axes` argument to `LinearOperator.transpose`.
- add `axes` argument to `LinearOperator.transpose`
- tests for `axes argument`
- better error checking for `LinearOperator.__call__`
- leaner implementation of `LinearOperator.size`
None
=> Add `axes` argument to `LinearOperator.transpose`

docs/source/development/pull_request.md
Added example of how to pass additional arguments to pytest via tox in dev guide. Reflects the changes made in #563 .
Closes #...
=> small addition to dev guide

src/probnum/randvars/_random_variable.py, src/probnum/typing.py, src/probnum/utils/argutils.py, tests/test_linops/test_linops.py, tests/test_randvars/test_normal.py, tests/test_utils/test_argutils.py
This PR refactors the `probnum.utils.as_numpy_scalar` to return scalar `np.ndarray`s instead of `np.number`s. This is preparation for PR #581, since JAX and PyTorch don't have array scalars.
=> Refactor `as_numpy_scalar` to produce scalar `np.ndarray`s

src/probnum/linops/_linear_operator.py, tests/test_linops/test_matrix.py
This PR fixes a bug, where the `__(r)matmul__` operator of a `Matrix` linear operator constructed from a `np.matrix` returns a `np.matrix` when being called with a `np.ndarray` as argument.
- previously, the last two assertions in the test I added were failing
None
=> `__(r)matmul__` of `Matrix` linear operator outputs `np.matrix`

docs/source/_templates/footer.html
Links pointing to Probabilistic Numerics content in the footer of the documentation were dead.
Links now point to the corresponding sections of www.probabilistic-numerics.org.
Closes #598
=> Correct links in footer of documentation

src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/linops/_scaling.py, tests/test_linops/test_linop_decompositions.py, tests/test_linops/test_linop_properties.py, tests/test_linops/test_linops.py, tests/test_linops/test_linops_cases/arithmetic_cases.py, tests/test_linops/test_linops_cases/kronecker_cases.py, tests/test_linops/test_linops_cases/linear_operator_cases.py, tests/test_linops/test_linops_cases/scaling_cases.py
This PR implements Cholesky decompositions for ProbNum's `linops` library.
To achieve this goal, I also had to implement symmetrization and parts of a matrix property system.
- `LinearOperator.cholesky(lower: bool) -> LinearOperator`
- `LinearOperator.symmetrize() -> LinearOperator` implementing "1/2 * (A + A^T)"
- Matrix properties
- `is_symmetric`
- `is_{upper,lower}_triangular`
- `is_positive_definite`
- Fixed bugs in `Kronecker.{inv,cond}`
- `_InverseLinearOperator` uses Cholesky factorization for SPD matrices
- Fixed bug in `_InverseLinearOperator` of singular matrix
- Added new tests and test cases
Implements parts of #569 and #571
=> Cholesky decompositions of `LinearOperator`s

docs/source/conf.py
Scipy apparently moved its intersphinx mapping (https://github.com/scipy/scipy/issues/14267). I am not sure why the doc-build still works, but it seems that the new address is https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/. 
This PR is split off from #626, to not interfere with merging the pytest version pin. If it should not be merged, then we can shoot down this one here instead of slowing the other one (no hard feelings in this case :)) .
=> Scipy intersphinx mapping update

.github/workflows/CI-build.yml
The bash uploader has been deprecated by codecov. This PR refactors the CI to use the new preferred way to upload coverage reports.
- use `codecov/codecov-action` to upload coverage reports
None
=> `codecov/codecov-action` instead of bash uploader

src/probnum/diffeq/odefilter/init_routines/_autodiff.py, tests/test_diffeq/test_odefilter/test_init_routines/test_init_routines.py
Rewrite the core implementation of `odefilter.init_routines.TaylorMode` into a more compact version and explain the background thoroughly.
No more early exits. No more confusing variable names. Transparent tuple/pytree usage. Let me know if something is not clear please!
=> Simplified TaylorMode implementation

src/probnum/_function.py, src/probnum/randprocs/kernels/_exponentiated_quadratic.py, src/probnum/randprocs/kernels/_kernel.py, src/probnum/randprocs/kernels/_rational_quadratic.py, tox.ini
Fixes a bug in `Kernel.__call__`, where scalar arguments produce incorrect outputs.
- `atleast_1d` -> `asarray` in `Kernel.__call__`
- Correct broadcasting behavior for scalar inputs and `Kernel`s with `input_shape=()`
- Make `output_shape` optional in `LambdaFunction.__init__`
None
=> [Bugfix] Scalar arguments in `Kernel.__call__`

src/probnum/_function.py, src/probnum/randprocs/_gaussian_process.py, src/probnum/randprocs/_random_process.py, src/probnum/randprocs/kernels/_kernel.py, src/probnum/randprocs/kernels/_matern.py, src/probnum/randprocs/markov/_markov_process.py, tests/test_randprocs/test_random_process.py
A few months ago, I redefined the shape of the outputs of `Kernel.__call__` to `cov.output_shape + batch_shape`.
However, this is very counterintuitive when in the context of random processes, since we would expect the outputs of the `mean`, `var`, and `std` functions to be `batch_shape + randproc.output_shape`, i.e. "the other way around".
My original change was made with multi-output GPs in mind, but even here it turns out that the `batch_shape + cov.output_shape`-order is easier to handle.
- rename `Kernel.{shape => output_shape}`
- change output shapes of `Kernel.{__call__, matrix}` to `batch_shape + kernel.output_shape`
- adapt random processes to these changes
- fixed a bug in `Matern` 3/2 kernel
- refactor `RandomProcess`
- add `input_ndim` and `output_ndim` as public arguments …
=> `Kernel.output_shape` semantics and further `RandomProcess` refactoring

.github/workflows/CI-build.yml, setup.cfg
This PR adds support for Python 3.10
- require Python >=3.8 but < 3.11
- Add conditional requirements on specific NumPy and SciPy versions, which introduced 3.10 support
- For some reason, `minimum-jaxlib` does not work under 3.10
Closes #633
=> Add support for Python 3.10

src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/randprocs/kernels/__init__.py, src/probnum/randprocs/kernels/_arithmetic.py, src/probnum/randprocs/kernels/_arithmetic_fallbacks.py, src/probnum/randprocs/kernels/_kernel.py, src/probnum/randprocs/kernels/_white_noise.py, tests/test_randprocs/test_kernels/conftest.py, tests/test_randprocs/test_kernels/test_arithmetic.py, tests/test_randprocs/test_kernels/test_arithmetic_fallbacks.py
This PR adds basic arithmetic for `Kernel`s. Kernel arithmetic allows user-friendly definition of custom kernels from existing ones.
This PR adds a `SumKernel`, `ScaledKernel` and `ProductKernel` as well as addition and multiplication of kernels. This allows the definition of kernels in the following fashion
```python
import numpy as np
from probnum.randprocs.kernels import ExpQuad, WhiteNoise
x = np.linspace(-1, 1, 5)
k = ExpQuad(input_shape=()) + 0.01 * WhiteNoise(input_shape=())
k.matrix(x)
"""
array([[1.01      , 0.8824969 , 0.60653066, 0.32465247, 0.13533528],
[0.8824969 , 1.01      , 0.8824969 , 0.60653066, 0.32465247],
[0.60653066, 0.8824969 , 1.01      , 0.8824969 , 0.60653066],
[0.32465247, 0.60653066, 0.8824969 , 1.01      , 0.8824969 ],
[0.13533528, 0.32465247, 0.60653066, …
```
=> Kernel arithmetic

benchmarks/linearsolvers.py, src/probnum/linalg/_bayescg.py, src/probnum/linalg/solvers/_state.py, src/probnum/linalg/solvers/information_ops/_projected_rhs.py, src/probnum/linalg/solvers/policies/_conjugate_gradient.py, src/probnum/linalg/solvers/stopping_criteria/_residual_norm.py, tests/test_linalg/test_solvers/test_policies/test_conjugate_gradient.py, tests/test_linalg/test_solvers/test_probabilistic_linear_solver/test_asymmetric.py, tests/test_linalg/test_solvers/test_probabilistic_linear_solver/test_symmetric.py, tests/test_linalg/test_solvers/test_state.py
This PR introduces the more commonly used definition of residual as `residual = y - y_approx` into `probnum.linalg` instead of `residual = y_approx - y`.
=> Consistent usage of "residual" in `probnum.linalg`

src/probnum/quad/solvers/policies/__init__.py, src/probnum/quad/solvers/policies/_policy.py, src/probnum/quad/solvers/policies/_random_policy.py
This PR moves the existing `quad` policies to separate modules. No functional changes.
This is one of the changes proposed in #620 
Closes #...
=> Moving `quad` policies to separate modules

src/probnum/randprocs/kernels/_arithmetic_fallbacks.py, tests/test_randprocs/test_kernels/test_arithmetic_fallbacks.py
Enables scaling a kernel with a negative value.
#654 introduced the possibility to multiply `Kernel`s scalar and the multiplication throws an exception in case this scalar is negative or 0. The latter is desirable in the context of covariance functions, since it ensures positive-semidefiniteness. However, `Kernel` is our interface for covariance functions as well as cross-covariance functions and in the case of cross-covariance functions, scaling with a negative value makes sense. For example, this happens if we want to compute the cross-covariance between a GP and its negative.
None
=> Remove restriction for negative scalars in `ScaledKernel`

src/probnum/randprocs/kernels/_product_matern.py, tests/test_quad/test_kernel_conversion.py
The parameter expansion of `ProductMatern` now catches cases where `lengthscales` and `nus` are given by `numpy.ndarray`s of shape `()`. This was actually a bug since it broke some kernel conversion in `quad`. I added a test to catch the latter.
Bug in `quad` was introduced in #583 .
Closes #...
=> Fixing parameters expansion in `ProductMatern`

benchmarks/linearsolvers.py, benchmarks/randprocs.py, tox.ini
This PR resolves pylint-ignore `line-too-long` message in `benchmark`. 
Removed the explicit pylint-ignore on the bottom of the tox.ini file for `benchmark`.
Closes #674
=> resolve pylint in benchmark for line-too-long

tests/test_quad/test_kernel_embeddings.py
This PR will hopefully fix the flaky kernel embedding test as linked in the issue.
- make test use the provided `rng` fixture
Closes #661
=> Fix flaky `quad` test.

docs/source/tutorials/linops/linear_operators_quickstart.ipynb, src/probnum/linalg/solvers/matrixbased.py, src/probnum/linops/__init__.py, src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/linops/_scaling.py, src/probnum/linops/_utils.py, tests/test_linops/test_linops_cases/linear_operator_cases.py, tests/test_randvars/test_normal.py
_matmul, _apply, _transpose etc. can now be implemented by overriding the corresponding methods in a subclass instead of passing the implementations in the constructor. The previous approach is still possible via the new LambdaLinearOperator.
* Refactor LinearOperator such that method implementations are provided via subclass overrides
* Introduce LambdaLinearOperator subclass which provides support for the old approach of passing method implementations via the constructor
* Replace all previous uses of LinearOperator with LambdaLinearOperator to maintain compatibility
=> Refactor LinearOperator for method overriding

src/probnum/linops/_linear_operator.py, tests/test_linops/test_linops_cases/linear_operator_cases.py
Currently, executing
```python
A = pn.linops.Matrix(...)
x1 = A.inv() @ b1
x2 = A.inv() @ b2
```
runs `scipy.linalg.lu_factor` on `A.dense` twice.
In principle, it would be possible to cache the return value of `A.inv()`, but that would introduce cyclic references,
which might cause memory overhead before being collected by the garbage collector.
An elegant solution is to cache all expensive quantities in the linear operator `A` itself, and then create "throwaway" objects like `_InverseLinearOperator` and `TransposeLinearOperator`, which are essentially views of `A`, accessing these quantities through the base linear operator.
- caching of LU decomposition in `LinearOperator`s
- bugfix in `_InverseLinearOperator.__rmatmul__`
- add test case for `_InverseLinearOperator`
- Replace custom …
=> Caching of the LU decomposition computed by `_InverseLinearOperator`

src/probnum/quad/kernel_embeddings/_kernel_embedding.py
So far the `quad` docs do not mention anywhere which kernel embeddings are available for Bayesian quadarture. This PR adds this info to the docs. 
Further, made the helper function that checks the kernel-measure pair into a staticmethod as it made sense.
Closes #...
=> adding some info to `quad` docs.

docs/notebook-requirements.txt
Due to a bug introduced in IPython 8.7 (https://github.com/ipython/ipython/issues/13845) our doc build started failing on readthedocs with warnings like these:
```bash
/home/docs/checkouts/readthedocs.org/user_builds/probnum/checkouts/746/docs/source/tutorials/quickstart.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known
```
This PR pins the version of IPython in the documentation requirements.
=> Pinned IPython version to fix bug in documentation build

src/probnum/quad/_utils.py, src/probnum/quad/integration_measures/_integration_measure.py, src/probnum/quad/integration_measures/_lebesgue_measure.py, tests/test_quad/test_bq_utils.py, tests/test_quad/test_integration_measure.py
This PR removes the default rng from the `quad` integration measures. Further, some long overdue shape tests for the sample method of the measures are added.
na
Closes #...
=> Make `quad` integration measures stateless 

dev-requirements.txt, tox.ini
The documentation build is failing with the following output:
```bash
docs: failed with make is not allowed, use allowlist_externals to allow it
.pkg: _exit> python /opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
docs: FAIL code 1 (103.39 seconds)
evaluation failed :( (103.66 seconds)
```
This seems to be caused by a change in the tox configuration for external tools like `make`.
=> Updated tox configuration with new keyword for externals

src/probnum/randvars/_scipy_stats.py
SciPy 1.10 introduced a `Covariance` object (see https://scipy.github.io/devdocs/release.1.10.0.html#scipy-stats-improvements), which is being used for `multivariate_normal` random variables. This caused a bug in the `asrandvar` function which is handled in this PR.
=> Fix bug in `asrandvar` introduced by breaking changes in ScIPy 1.10

README.md
Due to a breaking change (https://github.com/badges/shields/issues/8671) in the behavior of status badges, the CI status was not displayed anymore. This PR corrects the link according to the recommendations in https://github.com/badges/shields/issues/8671.
=> CI status badge now displays correct status.

src/probnum/linops/_scaling.py, tests/test_linops/test_linops_cases/linear_operator_cases.py
matmul result now has the correct shape
The Zero linear operator had a bug where in the matmul implementation, it simply returned a zero vector of the same shape of the input. But this does not always match the shape we expect from the matmul output.
Closes #761
=> Fix matmul implementation of Zero linop

src/probnum/linops/_linear_operator.py
Transposing a Matrix now maintains symmetry and positive definiteness - if the original Matrix had them. It also flips triangular properties.
- Extend previous implementation of _transpose for Matrix
- If original Matrix is lower/upper triangular, transposed Matrix is upper/lower triangular
- If original Matrix is symmetric/positive definite, transposed Matrix is symmetric/positive definite
I am not sure if this is the right way to do it. I know that _TransposedLinearOperator already keeps these properties, but this only comes into play when the user doesn't provide a custom _transpose implementation. I think it might make sense to - more generally - transfer these properties in LinearOperator's transpose before returning the transposed linop object. But I was a bit hesitant to do that …
=> Make Matrix transpose keep some properties

src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/linops/_scaling.py, src/probnum/linops/_vectorize.py, tests/test_linops/test_linops.py, tests/test_linops/test_linops_cases/arithmetic_cases.py, tests/test_linops/test_linops_cases/linear_operator_cases.py, tests/test_linops/test_matrix.py
This PR adds the method `solve` to the `LinearOperator` interface.
- `LinearOperator.solve`
- `_InverseLinearOperator` uses `LinearOperator.solve` as `_matmul`
- remove redundant `rmatmul` argument in `LambdaLinearOperator`
None
=> `LinearOperator.solve` method

docs/notebook-requirements.txt
Fix the matplotlib version used to generate plots in the tutorials and documentation.
The tutorial notebooks started failing after #780 was merged with the following error:
```sh
[NbConvertApp] Converting notebook ./docs/source/tutorials/linalg/linear_solvers_quickstart.ipynb to notebook
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/jupyter-nbconvert", line 8, in <module>
sys.exit(main())
File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_core/application.py", line 277, in launch_instance
return super().launch_instance(argv=argv, **kwargs)
File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
app.start()
File …
```
=> Specify matplotlib version for notebooks

src/probnum/randprocs/kernels/_kernel.py
This PR splits the `input_shape` of a `Kernel` into separate input shapes for the two arguments. With this change, we can model cross-covariance functions of random processes with different domains.
- split `Kernel.input_shape` into `Kernel.input_shape_{0,1}`
- retain `Kernel.input_shape` as a convenience argument if `input_shape_0 == input_shape_1`
- the same is done for `input_{ndim_size}`
None
=> Split `Kernel.input_shape` into `Kernel.input_shape_{0,1}`

benchmarks/asv.conf.json, benchmarks/requirements.txt, tox.ini
Adds a custom build command for the benchmarks and a `asv check` to the github action.
Tries to address the issues raised in #787. The problem was presumably that probnum was not properly installed into the virtualenv that was used for benchmarking.
Closes #787
=> Fix to benchmark runner by adding custom build command

setup.py, src/probnum/randprocs/covfuncs/__init__.py, src/probnum/randprocs/covfuncs/_covariance_function.py, src/probnum/randprocs/covfuncs/_covariance_linear_operator.py, src/probnum/randprocs/covfuncs/_exponentiated_quadratic.py, src/probnum/randprocs/covfuncs/_matern.py, tests/test_randprocs/test_covfuncs/test_linop_matrix.py
Enable efficient matrix-free implementations of covariance linear operators via KeOps
The overall idea is inspired by @JonathanWenger's KeOps integration in IterGP.
- Add new method _keops_lazy_tensor that can be implemented in a subclass to return the LazyTensor equivalent of _evaluate_matrix
- Add new class CovarianceLinearOperator that represents the pairwise covariances and uses KeOps by default (if possible)
- Add KeOps implementations for Matern and ExpQuad
One problem I came across is that by making KeOps optional (implemented via import guards), we cannot use KeOps typing in function signatures because otherwise everything breaks for users who do not have KeOps installed. Any ideas on this?
EDIT: And I guess the CI tests are also problematic because they don't have KeOps installed …
=> Add KeOps support to CovarianceFunction

src/probnum/linops/__init__.py, src/probnum/linops/_block.py, tests/test_linops/test_block.py, tests/test_linops/test_linops.py, tests/test_linops/test_linops_cases/block_cases.py
Add a custom linear operator `BlockDiagonalMatrix` for block diagonal structures.
- Add `BlockDiagonalMatrix` along with custom implementations of `det`, `trace`, `eigvals`, etc...
- Add two test cases for it
- Fix bug in eigvals test. Previously this checked the arrays returned by `linop` and `matrix` for equality. But the eigenvalues may have a different order. For the comparison to be valid, we need to sort the arrays before comparing them.
=> Add `BlockDiagonalMatrix`

src/probnum/randprocs/covfuncs/_covariance_function.py, src/probnum/randprocs/covfuncs/_covariance_linear_operator.py
Bugfix in transpose of `CovarianceLinearOperator`
The previous `_transpose` implementation only worked for the case that both inputs are equal. The new implementation works for the general case where x0 and x1 may not be equal.
The new implementation now requires passing a callback `keops_lazy_tensor_fn` (as opposed to directly passing a `LazyTensor`) which the `CovarianceLinearOperator` can then pass on in `_transpose`.
=> Bugfix in `CovarianceLinearOperator` transpose

src/probnum/linops/_arithmetic.py
Previously, multiplying the Zero linear operator by a scalar would return a ScaledLinearOperator. But we can just directly return the original Zero linear operator. 
This simplifies composed linear operators a little bit, particularly because the Zero linear operator can now be absorbed further, e.g. in a sum. Consider the following snippet:
```python
>>> from probnum.linops import Zero, Identity
>>> i = Identity((20, 20))
>>> z = Zero((20, 20))
>>> i + 3 * z
SumLinearOperator [
<Identity with shape=(20, 20) and dtype=float64>,
3.0 * <Zero with shape=(20, 20) and dtype=float64>
]
```
With this change, the result is
```python
>>> i + 3 * z
<Identity with shape=(20, 20) and dtype=float64>
```
=> Make scalar * Zero = Zero

src/probnum/linops/_arithmetic_fallbacks.py, src/probnum/linops/_block.py, src/probnum/linops/_kronecker.py, src/probnum/linops/_linear_operator.py, src/probnum/linops/_scaling.py, tests/test_linops/test_linops.py
Add `LinearOperator.diagonal()`.
... which computes the diagonal of the linear operator. Default implementation uses `np.diagonal`, and subclasses may use more efficient implementations, e.g. for Kronecker linear operators.
- Figure out a good way to compute the diagonal of a kronecker product when the second factor is not square
- Implement diagonal of a covariance linear operator (shouldn't be too hard since it gets both inputs as arguments, but then you would possibly have to reshape and call the covariance function so that it only computes the diagonal)
=> Linop diagonal
