probabilistic-numerics/probnum

- src/probnum/linalg/linearsolvers/linearsolvers.py
- src/probnum/linalg/linops/kronecker.py
- src/probnum/optim/optim.py
- src/probnum/optim/stoppingcriterion/stoppingcriterion.py
This PR does not include the removal of the assert statements in `./src/probnum/prob/randomprocess/randomprocesses.py`, because I had the impression that this topic is still in active development (see #44).
> Remove asserts (fixes #62)

- src/probnum/optim/stoppingcriterion/stoppingcriterion.py
Closes #80 
The discussion in #80 provides some more details on this PR. Most changes are trivial and fix wrong conditional if statements,. The fix in `./tests/test_optim/test_stoppingcriterion/test_stoppingcriterion.py:51` was suggested by @pnkraemer.
> Fix failing tests

- src/probnum/diffeq/ode/ivp.py
- src/probnum/diffeq/odefiltsmooth/prior.py
- tests/test_diffeq/test_ode/test_ivp.py
- tests/test_diffeq/test_odefiltsmooth/test_ivp2filter.py
Unittests for ivp2filter (roughly: output is the correct filter, measurementmodel is as expected, initial distribution matches) and some more for ivp (base tests were there, added tests for jacobians of lotkavolterra, fitzhughnagumo, logistic via finite differences)
> With nathanael

- src/probnum/diffeq/ode/ivp.py
- src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
- src/probnum/filtsmooth/gaussfiltsmooth/unscentedtransform.py
- src/probnum/filtsmooth/statespace/discrete/discretegaussianmodel.py
- src/probnum/filtsmooth/statespace/discrete/discretemodel.py
There is one commit which says that randomprocesses are removed from git but kept locally. That did not work, they are still in the git. This will be the next task
> Diffeq - removed todos and zombie code

- src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
- src/probnum/diffeq/odefiltsmooth/odefiltsmooth.py
- src/probnum/diffeq/steprule.py
- src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py
Open TODO: Write a `_get_steprule` function to get that complexity into it's separate function.
> Opinionated refactoring: Changed/removed docstrings, functions, variable names, with the goal on making the code more explicit

- .travis.yml
- setup.cfg
This PR updates some configuration files in a minor way by updating writing style, some comments and the required Python version.
> Minor updates to config files

- .github/workflows/linting.yml
Fixes the pylint errors that block #224 and #225.
> Fix pylint errors by pinning the Python version in the Github workflows

- src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
- src/probnum/filtsmooth/gaussfiltsmooth/kalman.py
> Change update signature in Kalman

- src/probnum/diffeq/odesolver.py
> Fix the order of callback and saving in ODESolver.solve

- src/probnum/filtsmooth/statespace/sde.py
> Fixed RK4 in statistics of linear SDEs

- setup.cfg
- src/probnum/problems/__init__.py
- src/probnum/problems/_problems.py
This is a work in progress regarding #279 .
I decided to go for something like named tuples, because I think this problem interface should be super light-weight and I do not encourage anyone to let it be more than a collection of attributes that define a PN-worthy problem.
I chose dataclasses, because namedtuples give rise to some really awkward documentation. Dataclasses seem to do the job well. If we decide to change any of these decisions, it should be pretty straightforward. 
Edit: Well well, for some reason I though we'd dropped 3.6 support. Looks like I was wrong.
> Problem interface

- src/probnum/filtsmooth/statespace/discrete_transition_utils.py
> Small bugfix to get the correct cholesky factors

- benchmarks/linops.py
> Linear Operator Benchmarks

- src/probnum/randvars/_normal.py
Issue: #421 
- removed `self._cov` and `self_mean` in `Normal` class as they seem obsolete.
- moved instance variable definition for cholesky functionality of `Normal` to after the `super` call.
> Removing obsolete instance variables in `Normal`

- README.md
follow up PR to #424 
Fixes a link in the Readme.md
> fix link in Readme.md

- docs/source/tutorials/odes/adaptive_steps_odefilter.ipynb
- docs/source/tutorials/odes/uncertainties_odefilters.ipynb
I've just fixed a few typos in the documentation. 
Thank you very much for the development and maintenance of this amazing package. I'm learning probabilistic numerics (applied to differential equations) and this package has been very helpful so far!
> Fix a few typos in the documentation 

- .github/CODEOWNERS
This PR makes the selection of CODEOWNERS much coarser
> Make selection of CODEOWNERS much coarser

- src/probnum/diffeq/stepsize/_steprule.py
Fix pylint errors for `stepsize`
> Fix pylint errors for `stepsize`

- src/probnum/diffeq/_perturbsolve_ivp.py
Fix pylint errors for `_perturbsolve_ivp.py`
> Fix pylint errors for `_perturbsolve_ivp.py`

- src/probnum/diffeq/_probsolve_ivp.py
- src/probnum/diffeq/_utils.py
Fix pylint errors for `_probsolve_ivp.py`.
> Fix pylint errors for `_probsolve_ivp.py`

- src/probnum/randprocs/_random_process.py
> Remove some abstractmethod-decorators from RandomProcess

- README.md
GitHub finally supports LaTeX Math in its Markdown flavor 🎉 
https://github.blog/2022-05-19-math-support-in-markdown/
- convert Unicode to LaTeX math in description of available solvers in `README.md`
None
> LaTeX Math in README.md

- src/probnum/linops/_linear_operator.py
The fallback implementations of methods in `LinearOperator` are now implemented in `_{method}` instead of in `{method}` after `_{method}` raised a `NotImplementedError`.
See above
None
> Fallback implementations of `LinearOperator` methods

- src/probnum/linops/_kronecker.py
This PR refactors the implementation of the linear operators in`_kronecker.py` to subclass directly from `LinearOperator` instead of from `LambdaLinearOperator`. This reduces complexity by a fair bit.
See above
None
> `{Identity,Symmetric}Kronecker` and `Symmetrize` implementation via subclassing

- src/probnum/linops/_linear_operator.py
This PR updates the `LinearOperator` class docstring.
See above.
None
> Update `LinearOperator` class docstring

- docs/source/tutorials/filtsmooth/continuous_linear_gaussian_filtering_smoothing.ipynb
- src/probnum/randvars/_random_variable.py
- src/probnum/typing.py
Just fixed a few typos in docs and docstrings.
> Fix a few typos
